name: CI Pipeline

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install pytest
      run: pip install pytest

    - name: Run unit tests
      run: pytest

    - name: Build Docker image
      run: docker build -t demo-app .

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install wget -y
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.50.0_Linux-64bit.deb

    - name: Scan image
      run: trivy image demo-app
